version: "3"

tasks:
  clean:
    - flutter clean

  format:
    - dart format ./lib/ --fix --line-length 110

  upgrade:
    - dart pub outdated --show-all
    - dart pub upgrade --major-versions
    - pnpm exec ncu -u
    - pnpm update

  # Dev

  dev:
    - flutter run

  # Build

  build:
    - flutter build {{.CLI_ARGS}}

  dev_web:
    - flutter run --web-renderer html

  build_web:
    cmds:
      - pnpm install
      - flutter build web --release --dart2js-optimization=O4 --web-renderer html
      - node --loader @swc-node/register/esm --no-warnings=ExperimentalWarning ./scripts/swc.ts
      # - pnpm exec parcel build
      # - cp -r --no-clobber ./build/web/assets ./build/web-dist
      # - cp -r --no-clobber ./build/web/canvaskit ./build/web-dist
      # - cp -r --no-clobber ./build/web/*.json ./build/web-dist
      # - cp -r --no-clobber ./build/web/*.js ./build/web-dist

  # Run

  run_windows:
    cmds:
      - task: build
        vars:
          CLI_ARGS: windows
      - ./build/windows/runner/Release/decide.exe

  run_web:
    - task: build_web
    # - pnpm exec servor ./build/web-dist
    - pnpm exec servor ./build/web
